import { Candidate } from "./types";

export const INITIAL_CANDIDATES: Candidate[] = [
  // --- Bar Benders ---
  {
    id: "cand-001",
    positionId: "bar_bender",
    name: "Somapala Perera",
    referenceId: "BB-2201",
    date: "2026-07-10",
    assessor: "Eng. Gamage",
    contact: "+94 77 123 4567",
    s1_siteExperience: 90,
    s1_nvqQualification: 83,
    s1_recommendation: 90,
    s2_measurementReading: 90,
    s2_machineKnowledge: 80,
    s2_methodology: 84,
    s2_hseEquipment: 90,
    s3_physicalAppearance: 88,
    s3_healthCondition: 92,
    s3_characterAttitude: 87,
    s3_extendedHours: 90,
    practicalTestRequired: true,
    notes: "Outstanding candidate with extensive site experience. Showed excellent performance on standard bar bending schedule drawing tests during the interview. Safe worker who follows all HSE rules.",
    status: "Selected",
    isHundredScale: true
  },
  {
    id: "cand-002",
    positionId: "bar_bender",
    name: "Arjun Kumar",
    referenceId: "BB-2202",
    date: "2026-07-12",
    assessor: "Supervisor Fernando",
    contact: "+94 71 987 6543",
    s1_siteExperience: 56,
    s1_nvqQualification: 50,
    s1_recommendation: 60,
    s2_measurementReading: 50,
    s2_machineKnowledge: 70,
    s2_methodology: 60,
    s2_hseEquipment: 70,
    s3_physicalAppearance: 96,
    s3_healthCondition: 92,
    s3_characterAttitude: 83,
    s3_extendedHours: 95,
    practicalTestRequired: true,
    notes: "Physically very fit and eager to work extended shifts. However, his measurement reading and blueprint interpretation skills are weak. Needs additional supervision and training, but demonstrates high potential.",
    status: "On Hold",
    isHundredScale: true
  },
  {
    id: "cand-003",
    positionId: "bar_bender",
    name: "Chen Wei",
    referenceId: "BB-2203",
    date: "2026-07-13",
    assessor: "Eng. Gamage",
    contact: "chen.wei@construction-hub.com",
    s1_siteExperience: 96,
    s1_nvqQualification: 93,
    s1_recommendation: 95,
    s2_measurementReading: 95,
    s2_machineKnowledge: 90,
    s2_methodology: 92,
    s2_hseEquipment: 80,
    s3_physicalAppearance: 84,
    s3_healthCondition: 88,
    s3_characterAttitude: 80,
    s3_extendedHours: 75,
    practicalTestRequired: false,
    notes: "Very strong overseas background. Highly recommended by current site supervisors. We need to conduct his practical test (on-site steel cutting & assembly speed) before making a final selected decision.",
    status: "Pending Practical",
    isHundredScale: true
  },
  {
    id: "cand-004",
    positionId: "bar_bender",
    name: "Kamal Silva",
    referenceId: "BB-2204",
    date: "2026-07-08",
    assessor: "Supervisor Fernando",
    contact: "+94 72 444 5555",
    s1_siteExperience: 30,
    s1_nvqQualification: 17,
    s1_recommendation: 30,
    s2_measurementReading: 40,
    s2_machineKnowledge: 50,
    s2_methodology: 36,
    s2_hseEquipment: 40,
    s3_physicalAppearance: 72,
    s3_healthCondition: 76,
    s3_characterAttitude: 40,
    s3_extendedHours: 50,
    practicalTestRequired: false,
    notes: "Low competency score across knowledge domains. Failed to correctly read simple bar bending schedules. Flagged for legal status during background self-disclosure.",
    status: "Rejected",
    isHundredScale: true
  },
  
  // --- Finishing Carpenters ---
  {
    id: "cand-101",
    positionId: "finishing_carpenter",
    name: "Ruwan Jayasinghe",
    referenceId: "FC-3101",
    date: "2026-07-11",
    assessor: "Master Carpenter Perera",
    contact: "+94 77 999 1122",
    s1_siteExperience: 94,
    s1_nvqQualification: 87,
    s1_recommendation: 90,
    s2_measurementReading: 100,
    s2_machineKnowledge: 90,
    s2_methodology: 90,
    s2_hseEquipment: 90,
    s3_physicalAppearance: 80,
    s3_healthCondition: 88,
    s3_characterAttitude: 93,
    s3_extendedHours: 75,
    practicalTestRequired: true,
    notes: "Superb cabinetry installer. Practically flawless joints and alignment. Very familiar with high-end miter saws and routing rigs. Recommended for immediate selection.",
    status: "Selected",
    isHundredScale: true
  },
  {
    id: "cand-102",
    positionId: "finishing_carpenter",
    name: "James Miller",
    referenceId: "FC-3102",
    date: "2026-07-12",
    assessor: "Master Carpenter Perera",
    contact: "james.m@carpentryinc.com",
    s1_siteExperience: 60,
    s1_nvqQualification: 40,
    s1_recommendation: 70,
    s2_measurementReading: 60,
    s2_machineKnowledge: 75,
    s2_methodology: 64,
    s2_hseEquipment: 80,
    s3_physicalAppearance: 88,
    s3_healthCondition: 72,
    s3_characterAttitude: 80,
    s3_extendedHours: 90,
    practicalTestRequired: false,
    notes: "Competent basic carpentry skills. Has experience with door frame installation but needs testing on precision veneer and crown molding joinery before confirmation.",
    status: "Pending Practical",
    isHundredScale: true
  },

  // --- Labours ---
  {
    id: "cand-201",
    positionId: "labour",
    name: "Sunil Perera",
    referenceId: "LA-4011",
    date: "2026-07-09",
    assessor: "Foreman Bandara",
    contact: "+94 75 555 6677",
    s1_siteExperience: 80,
    s1_nvqQualification: 67,
    s1_recommendation: 75,
    s2_measurementReading: 75,
    s2_machineKnowledge: 80,
    s2_methodology: 88,
    s2_hseEquipment: 100,
    s3_physicalAppearance: 100,
    s3_healthCondition: 100,
    s3_characterAttitude: 93,
    s3_extendedHours: 100,
    practicalTestRequired: true,
    notes: "A stellar worker with maximum fitness scores. Excellent discipline, follows instructions perfectly, always wears safety equipment properly, and works overtime without complaint.",
    status: "Selected",
    isHundredScale: true
  },
  {
    id: "cand-202",
    positionId: "labour",
    name: "Kumar Selvam",
    referenceId: "LA-4012",
    date: "2026-07-14",
    assessor: "Foreman Bandara",
    contact: "+94 77 443 2123",
    s1_siteExperience: 36,
    s1_nvqQualification: 33,
    s1_recommendation: 40,
    s2_measurementReading: 55,
    s2_machineKnowledge: 60,
    s2_methodology: 50,
    s2_hseEquipment: 60,
    s3_physicalAppearance: 96,
    s3_healthCondition: 88,
    s3_characterAttitude: 67,
    s3_extendedHours: 80,
    practicalTestRequired: true,
    notes: "Fit worker, but has minimal construction site exposure. Needs continuous monitoring on safety compliance (scaffold boundaries and mask discipline).",
    status: "On Hold",
    isHundredScale: true
  },

  // --- Masons ---
  {
    id: "cand-301",
    positionId: "mason",
    name: "Nimal Fernando",
    referenceId: "MA-5110",
    date: "2026-07-11",
    assessor: "Eng. Gamage",
    contact: "+94 71 332 2110",
    s1_siteExperience: 92,
    s1_nvqQualification: 80,
    s1_recommendation: 85,
    s2_measurementReading: 85,
    s2_machineKnowledge: 75,
    s2_methodology: 90,
    s2_hseEquipment: 80,
    s3_physicalAppearance: 92,
    s3_healthCondition: 92,
    s3_characterAttitude: 90,
    s3_extendedHours: 90,
    practicalTestRequired: true,
    notes: "Outstanding bricklayer. Perfect alignments during the test brick columns, with flawless joint thickness and plaster finishing. Highly recommended.",
    status: "Selected",
    isHundredScale: true
  }
];
